name: Lint Code

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest'

    - name: Install dependencies
      run: bun install

    - name: Run linter
      run: bun run lint
